name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses:
          actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Set version dynamically
      - name: Set Image Version
        id: vars
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t 27099817/todo-app-backend:${{ env.IMAGE_TAG }} .
          docker push 27099817/todo-app-backend:${{ env.IMAGE_TAG }}

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      # Set up kubectl
      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Configure kubectl for EKS
      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name todo-app-cluster

      # Deploy with Helm
      - name: Deploy with Helm
        run: |
          helm upgrade --install todo-app-backend ./todo-app-backend \
            --set image.repository=27099817/todo-app-backend \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --namespace default \
            --create-namespace
